version: '1'
services:
  client:
    container_name: crowd_funding_dashboard_frontend
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 127.0.0.1:5173:5173
    volumes:
      - ./client:/app/client
      - /app/client/node_modules 
    environment: 
      - CHOKIDAR_USEPOLLING=true

  web3:
    container_name: crowd_funding_dashboard_web3
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 127.0.0.1:5232:5232
    volumes:
      - ./web3/:/web3/app
      - /app/web3/node_modules 
  